### ISSUE TITLE
Invisible DXF-Layers are shown in Layer-Sidebar but not visible on Map

### ISSUE THREAD

**Issue by batzillm** [EZUSoft/AnotherDXF2Shape#1]
Hi,
best solution and great tool to import DXF with wrong georeference! Thanks!
Issue:
The import of all Layers available in the DXF-File works and all Layers are imported to the shapefile and added to the QGIS-Sidebar. Unfortunately, the layers which were set invisible when the DXF-File was saved are not shown in the map. Qgis gets the correct number of objects in the layer (right click => show number of objects) but whatever i try to change in the QGIS-Layer i am not able to get the formerly invisible layers to be shown.

Am i missing something?
In the QGIS Default DXF Import-Tool, there is the possibility to select/deselect layers when importing but that does not help me since i am not able to georeference in this tool.
Thanks! Merlin

**Comment by EZUSoft** [comment]
I think you need to adjust the rendering in QGIS. 
Please send me the DXF or make it available for download.

**Comment by batzillm** [comment]
Issue is resolved thanks to Mike. Root cause of the issue was the exporting CAD-Programm which sets the color of invisible layers to #00000000 (8 digit instead of 6 for a correct HEX-Color). When changing the value in the color-column of the layer attribute table to a correct HEX color, everything works smoothly.
Alternatively the automatic color setting from the attribute table can be deactivated to set the layer color manually
![grafik](https://user-images.githubusercontent.com/2981220/230198159-cee37938-de1d-466a-b249-d7f49129a2b6.png)
