### ISSUE TITLE
Home page link wrong

### ISSUE THREAD

**Issue by pcav** [EZUSoft/AnotherDXF2Shape#1]
Please fix

**Comment by EZUSoft** [comment]
Hi,
the link to http://forum.makobo.de/viewtopic.php?f=3&t=39 should work. I can not find any mistakes

**Comment by pcav** [comment]
The link in: http://plugins.qgis.org/plugins/AnotherDXF2Shape/
is:
http://www.makobo.de/links/Forum_AnotherDXF2Shape.php
which goes to:
http://forum.makobo.de/viewtopic.php?f=3&t=39
all in German. Please point to an English page.
Thanks.

**Comment by EZUSoft** [comment]
Hi,
I've revised the plugin, adapted the homepage and created an English documention.
I hope it's ok that way :-)
