### ISSUE TITLE
how does it convert DWG to SHP?

### ISSUE THREAD

**Issue by Jerry-goodboy** [EZUSoft/AnotherDXF2Shape#10]
how does it convert DWG to SHP? Now the plugin just convert DXF to SHP

**Comment by EZUSoft** [comment]
For DWG you can use the direct QGIS import from V2.18.2.

Project --> DWG/DXF Import

**Comment by Jerry-goodboy** [comment]
Yes, I'm using QGIS 3.6, macOS 10.14.5, DWG from AutoCAD 2004/2005/2006 and it contains Chinese characters when I used the way of "Project --> DWG/DXF Import", it works, but the Chinese characters are garbled, and I could not figure out how to solve this problem, It took me two days to search the answer over the web, Unfortunately, I didn't find anything useful. So I wanna get your help, thx

**Comment by EZUSoft** [comment]
My plugin has nothing to do with this QGIS feature. I can not help you there. Here you have to turn directly to the QGIS development.

**Comment by Jerry-goodboy** [comment]
OK, thx a lot
