### ISSUE TITLE
3D dxf

### ISSUE THREAD

**Issue by MaticDiba** [EZUSoft/AnotherDXF2Shape#11]
Hi, 
I'm trying to import DXF file that represents 3D object. If I import it with normal import I loose the layer structure, so I decided to use your plugin which works perfectly except I loose Z coordinate. Why would that be?

My next step is generation of 3d model with Qgis2threejs, but the result of your plugin import is not 3D. 

If you want I can send you the dxf file.

Any help would be much appreciated.

**Comment by EZUSoft** [comment]
Version 1.0.7 now has an option to use 3D
