### ISSUE TITLE
rgb colours not preserved

### ISSUE THREAD

**Issue by AlisterH** [EZUSoft/AnotherDXF2Shape#13]
Hi, thanks for the very useful plugin.
I found that in addition to the numbered colours 1-255, DXF supports colours specified simply by their rgb value.  This plugin does not preserve those colours - see screenshots.  Do you think it is an upstream issue i.e. gdal/ogr?
I get a similar result when I save from Autocad to a very old version of DXF, which I presume only supports the numbered colours 1-255.

Original dxf:
![image](https://user-images.githubusercontent.com/714600/69393513-42519e00-0d3e-11ea-821e-7e7e4c4d6c2b.png)
QGIS:
![image](https://user-images.githubusercontent.com/714600/69393599-7dec6800-0d3e-11ea-9368-6106244d1813.png)
DXF file:
[test1.zip](https://github.com/EZUSoft/AnotherDXF2Shape/files/3877718/test1.zip)

**Comment by EZUSoft** [comment]
The plugin works with OGR. It can only use the colors generated by the OGR. If you look at the attributes of the surfaces, you can see this (ogr_style).
