### ISSUE TITLE
3D geometries being converted to 2D

### ISSUE THREAD

**Issue by augviewmike** [EZUSoft/AnotherDXF2Shape#18]
current release appears to convert 3D dxf geometries into 2D on import.

**Comment by EZUSoft** [comment]
- metadate.txt: 09.07.19 V1.0.7  - Optional 3D

![DXF3D](https://user-images.githubusercontent.com/19267407/109413285-e64bdf80-79ac-11eb-9397-774a2b290c78.png)

**Comment by EZUSoft** [comment]
Thanks for the hint. I'll upload the correction tomorrow.

**Comment by EZUSoft** [comment]
01.03.21 V1.2.2
    - Correction of 3D support for GeoPackage
