### ISSUE TITLE
DXF Import dimensional conversion Issue?

### ISSUE THREAD

**Issue by Mac-in-Memphis** [EZUSoft/AnotherDXF2Shape#19]
Mike. 
I really appreciate your add-in! The transformation offset function is a superior tool! 
I'm not sure if this is a CRS issue on my side, but when importing a 1:1 scaled DXF onto QGIS, my QGIS result is slightly smaller than the dimensions of the original CAD object. 
I can forward more specifics if you wish.
Again, I really appreciate your work!  
I will continue to use your addin, for generalized and/or upscaled vector imports.
Please advise, if I'm using the your add-in beyond its intended scope, or incorrectly.
Best Regards, Mac in Memphis
QGIS 3.16.1 / AnotherDXF2Shape v.1.2.3 / GDAL 3.1.4 / Dell PC / WIN10 Pro.

**Comment by EZUSoft** [comment]
Hello,
a DXF has no CRS and no units of measurement. The coordinates are initially just numbers.
With which units (e.g. meters, inches) and in which CRS should the DXF be imported?
It would be good if you send me the DXF by email.

**Comment by Mac-in-Memphis** [comment]
Hi!
Thank you for your prompt response!
I've sent two emails to your q**s@m*****.d* address...
with detailed explainations.
I've not yet used PM in GitHub, but if you didn't get them, then I will learn.

Attached is a very simple DXF within a zipped folder, which can be used as a quick test.
[6000M-R-circle1.zip](https://github.com/EZUSoft/AnotherDXF2Shape/files/6418197/6000M-R-circle1.zip)
.

**Comment by EZUSoft** [comment]
Hello,
the way you use the program, there is no scaling.
The coordinates are only shifted.
All further adjustments are made by your CRS specification.


**You are not confusing Cartesian and Ellipsoidal distance.**
