### ISSUE TITLE
suggestion: translate control codes in MTEXT

### ISSUE THREAD

**Issue by AlisterH** [EZUSoft/AnotherDXF2Shape#2]
You could consider labelling with an expression to deal with the control codes that can be used in MTEXT:
https://help.autodesk.com/view/ACD/2022/ENU/?guid=GUID-518E1A9D-398C-4A8A-AC32-2D85590CDBE1
![image](https://user-images.githubusercontent.com/714600/235424030-78cba5a5-70fa-4d13-82ae-f2d6b87d0de0.png)

Unfortunately MTEXT can contain other garbage as well as these control codes for special characters , so I'm not sure that it can all be detected.

**Comment by EZUSoft** [comment]
Can you provide an example dxf file

**Comment by AlisterH** [comment]
Here are a few examples I've made, showing both usage of the diameter control code, and some of the garbage I was referring, which is all formatting related - tabs (of different types), font options etc.  
I was going to say most of this formatting probably isn't worth looking at, because of the limitations of labels in QGIS.  But it looks like you have already implemented support for MTEXT columns, simply creating a different feature for each column, and I guess it would be possible to implement more using the same approach.
This is what the files look like in CAD:
![image](https://user-images.githubusercontent.com/714600/235561359-1e8c0f42-f3c7-4a3c-8c57-fab0c2c52820.png)
![image](https://user-images.githubusercontent.com/714600/235561373-076c2297-2f88-43df-bc3f-c43996a81274.png)
![image](https://user-images.githubusercontent.com/714600/235561465-9c47c4f6-05f4-493c-aa37-f72e4edba96b.png)
[test mtext.zip](https://github.com/EZUSoft/AnotherDXF2Shape/files/11369070/test.mtext.zip)

**Comment by EZUSoft** [comment]
The new version V1.2.7 now has extended support for MTEXT
![MText](https://user-images.githubusercontent.com/19267407/235872715-106965c7-2d19-4fd6-bd66-71cc58419536.png)
---------------------------
It's not perfect, but better than importing from QGIS ;-)
![qgis](https://user-images.githubusercontent.com/19267407/235945320-f012141a-2bbd-4db3-9bd9-134a50be593b.png)

**Comment by pio-zie** [comment]
Another proposition about mtext objects.
As Autolisp programmer I'm using this routine:
http://www.lee-mac.com/lisp/html/GetTrueContent.html
you can find there a regexp expression which clear all garbage from mtext.

There also is stripmtext tool writen in lisp for that purposes which is aslo based on regexp:
https://cadabyss.wordpress.com
