### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [EZUSoft/AnotherDXF2Shape#2]
and check if your work could be integrated upstream.

**Comment by EZUSoft** [comment]
Hi,
AnotherDXF2Shape  is a QGIS-Plugin, which the DXF use in QGIS substantially improved.
  - Other elements than the standard import are displayed 
  - Display of text (Labeling)
  - Categorization by Layer
  - Group by Layer
  - Separate representation by layers possible

The plugin is a transitional solution. These options will  qgis offer in Version 2.18.
