### ISSUE TITLE
Unable to do bulk imports of DXF files

### ISSUE THREAD

**Issue by marcathian** [EZUSoft/AnotherDXF2Shape#20]
I am trying import a large set of DXF files using the  AnotherDXF2Shape plugin.  I have had success using a previous version in the past.  However with this current version I cannot get it to process more than 44 or 45 input files at at time.

Even though I have attempted to adjust the btnStart_clicked() method to pass only 20 files at a time from the selected list, it still crashes QGIS after 44 or 45 input files.

My current QGIS setup information is below:

QGIS version 3.20.3-Odense
QGIS code revision 495fbaecaf
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.2.2
PROJ version 7.2.1
EPSG Registry database version v10.008 (2020-12-16)
GEOS version 3.9.0-CAPI-1.16.2
SQLite version 3.34.1
PDAL version 2.2.0
PostgreSQL client version 13.4 (Ubuntu 13.4-0ubuntu0.21.04.1)
SpatiaLite version 5.0.1
QWT version 6.1.4
QScintilla2 version 2.11.6
OS version Ubuntu 21.04

Active Python plugins:
remotedebug
plugin_reloader
AnotherDXF2Shape
MetaSearch
db_manager
processing

**Comment by marcathian** [comment]
After some time I got to try it on a windows 10 VM.  It was able to process 383 files in a batch without crashing.

**Comment by EZUSoft** [comment]
Since the problem only appears to occur on Linux, there is not much I can do about it.
The problem is more likely to be in the QGIS memory management.
