### ISSUE TITLE
Import Text Angle

### ISSUE THREAD

**Issue by WGPSenshi** [EZUSoft/AnotherDXF2Shape#3]
Would it be possible to import the angle of text points (TEXTANGLE attribute)?

**Comment by EZUSoft** [comment]
The plugin use "OGR" to convert.
OGR does not support the output of the angle, so the value does not exist.
You can use the plugin "Dxf2Shp Converter". The shape produced contains the angle.

Note:
A new DXF interface will soon be installed in QGIS: 
https://drive.google.com/open?id=0B0h3PAH5uoY6c2hHTlBvWjdqQTQ

**Comment by WGPSenshi** [comment]
I've heard & read a lot about the new DXF support, but haven't heard anything about it actually being funded & in developement yet :( .

Dxf2shp does have that info, but doesn't have a lot of other stuff (really love your plugin for its layer-grouping and block-handling).

**Comment by EZUSoft** [comment]
The current version V0.5 now support **textangles** and other stuff like text size, text color, position (text-align), color, individual text formats
