### ISSUE TITLE
GUI import dialog almost unreadable on HiDPI

### ISSUE THREAD

**Issue by elpaso** [EZUSoft/AnotherDXF2Shape#4]
This is how the dialog appears on a 4k screen:

![immagine](https://cloud.githubusercontent.com/assets/142164/23014320/d00381cc-f42e-11e6-90db-ce2c413ad6a2.png)

**Comment by EZUSoft** [comment]
Thanks for the hint.
The current version V0.6 should now also work with high-resolution monitor.
