### ISSUE TITLE
3D / Z-Value

### ISSUE THREAD

**Issue by lukaszurbuchen** [EZUSoft/AnotherDXF2Shape#4]
3D-/Z-Values doesn't work. I've tried to import a triangular mesh from dxf with "Use 3D if possible". In the Vertex the Z-Value is na. The DXF has Z-Values. So I guess it is a bug.

**Comment by EZUSoft** [comment]
Please provide me with an example DXF

**Comment by lukaszurbuchen** [comment]
here is an example:
[example_3D.zip](https://github.com/EZUSoft/AnotherDXF2Shape/files/13669353/example_3D.zip)

**Comment by EZUSoft** [comment]
The “3DFACE” structure used cannot (currently) be converted to 3D. Try using normal polylines.
