### ISSUE TITLE
Enabling the plugin, is crashing qgis 3.0

### ISSUE THREAD

**Issue by antoniusz** [EZUSoft/AnotherDXF2Shape#8]
src/app/qgscustomization.cpp: 815: (customizeWidget) [0ms] QgsPluginManager x QDialog
src/app/pluginmanager/qgspluginmanager.cpp: 618: (pluginItemChanged) [5150ms]  Loading plugin: AnotherDXF2Shape
src/app/pluginmanager/qgspluginmanager.cpp: 259: (loadPlugin) [1ms] Loading Python plugin: AnotherDXF2Shape
QGIS died on signal 11[New LWP 19788]

**Comment by EZUSoft** [comment]
Which version of the plugin? Which operating system?

**Comment by antoniusz** [comment]
1.0.2, on Debian stretch, from https://qgis.org/debian-nightly-release repo.

**Comment by EZUSoft** [comment]
I have the latest version installed on debian 16.3 and it works for me:


```
QGIS version | 3.0.0-Girona | QGIS code revision | ec5a8a4
-- | -- | -- | --
Compiled against Qt | 5.7.1 | Running against Qt | 5.7.1
Compiled against GDAL/OGR | 2.1.2 | Running against GDAL/OGR | 2.1.2
Compiled against GEOS | 3.5.1-CAPI-1.9.1 | Running against GEOS | 3.5.1-CAPI-1.9.1 r4246
PostgreSQL Client Version | 9.6.6 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.2 | QScintilla2 Version | 2.9.3
PROJ.4 Version | 493
This copy of QGIS writes debugging output.
```

**Comment by antoniusz** [comment]
Uninstalling the python3-pyqt4 package resolved the problem.
