### ISSUE TITLE
NameError: name 'Helmert4Points' is not defined 

### ISSUE THREAD

**Issue by RaySarn** [EZUSoft/AnotherDXF2Shape#9]
Trying to import dxf file from LibreCAD.  I'm using the identical points transformation but keep getting the 'NameError: name 'Helmert4Points' is not defined'  What am I missing?  I'm running QGIS 3.2.2 and version 1.03 of the plugin.

**Comment by EZUSoft** [comment]
To be able to adjust the error, please send me the DXF and your transformation parameters.

**Comment by EZUSoft** [comment]
The version V1.0.4 should fixed the problem

**Comment by RaySarn** [comment]
Mike,

Thanks.  That problem went away with 1.04 as you suggested.  However, when
I tried it with the new version, I got a new error (see below). So this
sounds more like a problem with my input now. I'm new to QGIS. Is there a
tutorial someplace online for using this plugin?

Ray

IndexError: list assignment index out of range

Traceback (most recent call last):
  File "C:/Users/Ray/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AnotherDXF2Shape\uiADXF2Shape.py",
line 696, in btnStart_clicked
    Korrekt, DreiPassPunkte=self.CheckKonstTransWerte()
  File "C:/Users/Ray/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AnotherDXF2Shape\uiADXF2Shape.py",
line 382, in CheckKonstTransWerte
    p[row]=[[float(self.tabTPoints.item(row,0).text()),float(self.tabTPoints.item(row,1).text())],[float(self.tabTPoints.item(row,2).text()),float(self.tabTPoints.item(row,3).text())]]
IndexError: list assignment index out of range


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC
v.1900 64 bit (AMD64)]
QGIS version: 3.2.2-Bonn Bonn, 26842169e9

**Comment by EZUSoft** [comment]
I can not understand the mistake.
Please show a screenshot of your settings / your values

**Comment by EZUSoft** [comment]
Hello Ray, thanks for the feedback.
In the program, the code was only intended for 3 points.
The version V1.0.5 should fixed the problem.

**Comment by RaySarn** [comment]
Mike,

Thanks.  I'll update the version and give it a shot.  There  may still be
some user error on my part.  I'll let you know how it goes.

Ray

**Comment by RaySarn** [comment]
Mike,

Thanks for you help on this.  It has been working fine and I have used it
on several plats I am recreating.

Ray
